version: "3.8"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    environment:
      - MYSQL_DATABASE=videolitic
      - MYSQL_ROOT_PASSWORD=/run/secrets/db-password

  app:
    build: app
    restart: always
    volumes:
      - ./app/src:/code
    secrets:
      - db-password
    ports:
      - 80:5000
    networks:
      - backend-network

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backend-network:
